export interface Country {
  name: string;
  code: string;
  flag: string;
  dialCode: string;
}

export const countries: Country[] = [
  { name: 'Afghanistan', code: 'AF', flag: '🇦🇫', dialCode: '93' },
  { name: 'Afrique du Sud', code: 'ZA', flag: '🇿🇦', dialCode: '27' },
  { name: 'Albanie', code: 'AL', flag: '🇦🇱', dialCode: '355' },
  { name: 'Algérie', code: 'DZ', flag: '🇩🇿', dialCode: '213' },
  { name: 'Allemagne', code: 'DE', flag: '🇩🇪', dialCode: '49' },
  { name: 'Andorre', code: 'AD', flag: '🇦🇩', dialCode: '376' },
  { name: 'Angola', code: 'AO', flag: '🇦🇴', dialCode: '244' },
  { name: 'Antigua-et-Barbuda', code: 'AG', flag: '🇦🇬', dialCode: '1-268' },
  { name: 'Arabie Saoudite', code: 'SA', flag: '🇸🇦', dialCode: '966' },
  { name: 'Argentine', code: 'AR', flag: '🇦🇷', dialCode: '54' },
  { name: 'Arménie', code: 'AM', flag: '🇦🇲', dialCode: '374' },
  { name: 'Australie', code: 'AU', flag: '🇦🇺', dialCode: '61' },
  { name: 'Autriche', code: 'AT', flag: '🇦🇹', dialCode: '43' },
  { name: 'Azerbaïdjan', code: 'AZ', flag: '🇦🇿', dialCode: '994' },
  { name: 'Bahamas', code: 'BS', flag: '🇧🇸', dialCode: '1-242' },
  { name: 'Bahreïn', code: 'BH', flag: '🇧🇭', dialCode: '973' },
  { name: 'Bangladesh', code: 'BD', flag: '🇧🇩', dialCode: '880' },
  { name: 'Barbade', code: 'BB', flag: '🇧🇧', dialCode: '1-246' },
  { name: 'Belgique', code: 'BE', flag: '🇧🇪', dialCode: '32' },
  { name: 'Belize', code: 'BZ', flag: '🇧🇿', dialCode: '501' },
  { name: 'Bénin', code: 'BJ', flag: '🇧🇯', dialCode: '229' },
  { name: 'Bhoutan', code: 'BT', flag: '🇧🇹', dialCode: '975' },
  { name: 'Biélorussie', code: 'BY', flag: '🇧🇾', dialCode: '375' },
  { name: 'Birmanie (Myanmar)', code: 'MM', flag: '🇲🇲', dialCode: '95' },
  { name: 'Bolivie', code: 'BO', flag: '🇧🇴', dialCode: '591' },
  { name: 'Bosnie-Herzégovine', code: 'BA', flag: '🇧🇦', dialCode: '387' },
  { name: 'Botswana', code: 'BW', flag: '🇧🇼', dialCode: '267' },
  { name: 'Brésil', code: 'BR', flag: '🇧🇷', dialCode: '55' },
  { name: 'Brunei', code: 'BN', flag: '🇧🇳', dialCode: '673' },
  { name: 'Bulgarie', code: 'BG', flag: '🇧🇬', dialCode: '359' },
  { name: 'Burkina Faso', code: 'BF', flag: '🇧🇫', dialCode: '226' },
  { name: 'Burundi', code: 'BI', flag: '🇧🇮', dialCode: '257' },
  { name: 'Cambodge', code: 'KH', flag: '🇰🇭', dialCode: '855' },
  { name: 'Cameroun', code: 'CM', flag: '🇨🇲', dialCode: '237' },
  { name: 'Canada', code: 'CA', flag: '🇨🇦', dialCode: '1' },
  { name: 'Cap-Vert', code: 'CV', flag: '🇨🇻', dialCode: '238' },
  { name: 'Centrafrique', code: 'CF', flag: '🇨🇫', dialCode: '236' },
  { name: 'Chili', code: 'CL', flag: '🇨🇱', dialCode: '56' },
  { name: 'Chine', code: 'CN', flag: '🇨🇳', dialCode: '86' },
  { name: 'Chypre', code: 'CY', flag: '🇨🇾', dialCode: '357' },
  { name: 'Colombie', code: 'CO', flag: '🇨🇴', dialCode: '57' },
  { name: 'Comores', code: 'KM', flag: '🇰🇲', dialCode: '269' },
  { name: 'Congo (RDC)', code: 'CD', flag: '🇨🇩', dialCode: '243' },
  { name: 'Congo (République)', code: 'CG', flag: '🇨🇬', dialCode: '242' },
  { name: 'Corée du Nord', code: 'KP', flag: '🇰🇵', dialCode: '850' },
  { name: 'Corée du Sud', code: 'KR', flag: '🇰🇷', dialCode: '82' },
  { name: 'Costa Rica', code: 'CR', flag: '🇨🇷', dialCode: '506' },
  { name: 'Côte d\'Ivoire', code: 'CI', flag: '🇨🇮', dialCode: '225' },
  { name: 'Croatie', code: 'HR', flag: '🇭🇷', dialCode: '385' },
  { name: 'Cuba', code: 'CU', flag: '🇨🇺', dialCode: '53' },
  { name: 'Danemark', code: 'DK', flag: '🇩🇰', dialCode: '45' },
  { name: 'Djibouti', code: 'DJ', flag: '🇩🇯', dialCode: '253' },
  { name: 'Dominique', code: 'DM', flag: '🇩🇲', dialCode: '1-767' },
  { name: 'Égypte', code: 'EG', flag: '🇪🇬', dialCode: '20' },
  { name: 'Émirats arabes unis', code: 'AE', flag: '🇦🇪', dialCode: '971' },
  { name: 'Équateur', code: 'EC', flag: '🇪🇨', dialCode: '593' },
  { name: 'Érythrée', code: 'ER', flag: '🇪🇷', dialCode: '291' },
  { name: 'Espagne', code: 'ES', flag: '🇪🇸', dialCode: '34' },
  { name: 'Estonie', code: 'EE', flag: '🇪🇪', dialCode: '372' },
  { name: 'Eswatini', code: 'SZ', flag: '🇸🇿', dialCode: '268' },
  { name: 'États-Unis', code: 'US', flag: '🇺🇸', dialCode: '1' },
  { name: 'Éthiopie', code: 'ET', flag: '🇪🇹', dialCode: '251' },
  { name: 'Fidji', code: 'FJ', flag: '🇫🇯', dialCode: '679' },
  { name: 'Finlande', code: 'FI', flag: '🇫🇮', dialCode: '358' },
  { name: 'France', code: 'FR', flag: '🇫🇷', dialCode: '33' },
  { name: 'Gabon', code: 'GA', flag: '🇬🇦', dialCode: '241' },
  { name: 'Gambie', code: 'GM', flag: '🇬🇲', dialCode: '220' },
  { name: 'Géorgie', code: 'GE', flag: '🇬🇪', dialCode: '995' },
  { name: 'Ghana', code: 'GH', flag: '🇬🇭', dialCode: '233' },
  { name: 'Grèce', code: 'GR', flag: '🇬🇷', dialCode: '30' },
  { name: 'Grenade', code: 'GD', flag: '🇬🇩', dialCode: '1-473' },
  { name: 'Guatemala', code: 'GT', flag: '🇬🇹', dialCode: '502' },
  { name: 'Guinée', code: 'GN', flag: '🇬🇳', dialCode: '224' },
  { name: 'Guinée équatoriale', code: 'GQ', flag: '🇬🇶', dialCode: '240' },
  { name: 'Guinée-Bissau', code: 'GW', flag: '🇬🇼', dialCode: '245' },
  { name: 'Guyana', code: 'GY', flag: '🇬🇾', dialCode: '592' },
  { name: 'Haïti', code: 'HT', flag: '🇭🇹', dialCode: '509' },
  { name: 'Honduras', code: 'HN', flag: '🇭🇳', dialCode: '504' },
  { name: 'Hongrie', code: 'HU', flag: '🇭🇺', dialCode: '36' },
  { name: 'Îles Marshall', code: 'MH', flag: '🇲🇭', dialCode: '692' },
  { name: 'Îles Salomon', code: 'SB', flag: '🇸🇧', dialCode: '677' },
  { name: 'Inde', code: 'IN', flag: '🇮🇳', dialCode: '91' },
  { name: 'Indonésie', code: 'ID', flag: '🇮🇩', dialCode: '62' },
  { name: 'Irak', code: 'IQ', flag: '🇮🇶', dialCode: '964' },
  { name: 'Iran', code: 'IR', flag: '🇮🇷', dialCode: '98' },
  { name: 'Irlande', code: 'IE', flag: '🇮🇪', dialCode: '353' },
  { name: 'Islande', code: 'IS', flag: '🇮🇸', dialCode: '354' },
  { name: 'Israël', code: 'IL', flag: '🇮🇱', dialCode: '972' },
  { name: 'Italie', code: 'IT', flag: '🇮🇹', dialCode: '39' },
  { name: 'Jamaïque', code: 'JM', flag: '🇯🇲', dialCode: '1-876' },
  { name: 'Japon', code: 'JP', flag: '🇯🇵', dialCode: '81' },
  { name: 'Jordanie', code: 'JO', flag: '🇯🇴', dialCode: '962' },
  { name: 'Kazakhstan', code: 'KZ', flag: '🇰🇿', dialCode: '7' },
  { name: 'Kenya', code: 'KE', flag: '🇰🇪', dialCode: '254' },
  { name: 'Kirghizistan', code: 'KG', flag: '🇰🇬', dialCode: '996' },
  { name: 'Kiribati', code: 'KI', flag: '🇰🇮', dialCode: '686' },
  { name: 'Koweït', code: 'KW', flag: '🇰🇼', dialCode: '965' },
  { name: 'Laos', code: 'LA', flag: '🇱🇦', dialCode: '856' },
  { name: 'Lesotho', code: 'LS', flag: '🇱🇸', dialCode: '266' },
  { name: 'Lettonie', code: 'LV', flag: '🇱🇻', dialCode: '371' },
  { name: 'Liban', code: 'LB', flag: '🇱🇧', dialCode: '961' },
  { name: 'Liberia', code: 'LR', flag: '🇱🇷', dialCode: '231' },
  { name: 'Libye', code: 'LY', flag: '🇱🇾', dialCode: '218' },
  { name: 'Liechtenstein', code: 'LI', flag: '🇱🇮', dialCode: '423' },
  { name: 'Lituanie', code: 'LT', flag: '🇱🇹', dialCode: '370' },
  { name: 'Luxembourg', code: 'LU', flag: '🇱🇺', dialCode: '352' },
  { name: 'Macédoine du Nord', code: 'MK', flag: '🇲🇰', dialCode: '389' },
  { name: 'Madagascar', code: 'MG', flag: '🇲🇬', dialCode: '261' },
  { name: 'Malaisie', code: 'MY', flag: '🇲🇾', dialCode: '60' },
  { name: 'Malawi', code: 'MW', flag: '🇲🇼', dialCode: '265' },
  { name: 'Maldives', code: 'MV', flag: '🇲🇻', dialCode: '960' },
  { name: 'Mali', code: 'ML', flag: '🇲🇱', dialCode: '223' },
  { name: 'Malte', code: 'MT', flag: '🇲🇹', dialCode: '356' },
  { name: 'Maroc', code: 'MA', flag: '🇲🇦', dialCode: '212' },
  { name: 'Maurice', code: 'MU', flag: '🇲🇺', dialCode: '230' },
  { name: 'Mauritanie', code: 'MR', flag: '🇲🇷', dialCode: '222' },
  { name: 'Mexique', code: 'MX', flag: '🇲🇽', dialCode: '52' },
  { name: 'Micronésie', code: 'FM', flag: '🇫🇲', dialCode: '691' },
  { name: 'Moldavie', code: 'MD', flag: '🇲🇩', dialCode: '373' },
  { name: 'Monaco', code: 'MC', flag: '🇲🇨', dialCode: '377' },
  { name: 'Mongolie', code: 'MN', flag: '🇲🇳', dialCode: '976' },
  { name: 'Monténégro', code: 'ME', flag: '🇲🇪', dialCode: '382' },
  { name: 'Mozambique', code: 'MZ', flag: '🇲🇿', dialCode: '258' },
  { name: 'Namibie', code: 'NA', flag: '🇳🇦', dialCode: '264' },
  { name: 'Nauru', code: 'NR', flag: '🇳🇷', dialCode: '674' },
  { name: 'Népal', code: 'NP', flag: '🇳🇵', dialCode: '977' },
  { name: 'Nicaragua', code: 'NI', flag: '🇳🇮', dialCode: '505' },
  { name: 'Niger', code: 'NE', flag: '🇳🇪', dialCode: '227' },
  { name: 'Nigeria', code: 'NG', flag: '🇳🇬', dialCode: '234' },
  { name: 'Norvège', code: 'NO', flag: '🇳🇴', dialCode: '47' },
  { name: 'Nouvelle-Zélande', code: 'NZ', flag: '🇳🇿', dialCode: '64' },
  { name: 'Oman', code: 'OM', flag: '🇴🇲', dialCode: '968' },
  { name: 'Ouganda', code: 'UG', flag: '🇺🇬', dialCode: '256' },
  { name: 'Ouzbékistan', code: 'UZ', flag: '🇺🇿', dialCode: '998' },
  { name: 'Pakistan', code: 'PK', flag: '🇵🇰', dialCode: '92' },
  { name: 'Palaos', code: 'PW', flag: '🇵🇼', dialCode: '680' },
  { name: 'Panama', code: 'PA', flag: '🇵🇦', dialCode: '507' },
  { name: 'Papouasie-Nouvelle-Guinée', code: 'PG', flag: '🇵🇬', dialCode: '675' },
  { name: 'Paraguay', code: 'PY', flag: '🇵🇾', dialCode: '595' },
  { name: 'Pays-Bas', code: 'NL', flag: '🇳🇱', dialCode: '31' },
  { name: 'Pérou', code: 'PE', flag: '🇵🇪', dialCode: '51' },
  { name: 'Philippines', code: 'PH', flag: '🇵🇭', dialCode: '63' },
  { name: 'Pologne', code: 'PL', flag: '🇵🇱', dialCode: '48' },
  { name: 'Portugal', code: 'PT', flag: '🇵🇹', dialCode: '351' },
  { name: 'Qatar', code: 'QA', flag: '🇶🇦', dialCode: '974' },
  { name: 'Roumanie', code: 'RO', flag: '🇷🇴', dialCode: '40' },
  { name: 'Royaume-Uni', code: 'GB', flag: '🇬🇧', dialCode: '44' },
  { name: 'Russie', code: 'RU', flag: '🇷🇺', dialCode: '7' },
  { name: 'Rwanda', code: 'RW', flag: '🇷🇼', dialCode: '250' },
  { name: 'Saint-Christophe-et-Niévès', code: 'KN', flag: '🇰🇳', dialCode: '1-869' },
  { name: 'Sainte-Lucie', code: 'LC', flag: '🇱🇨', dialCode: '1-758' },
  { name: 'Saint-Vincent-et-les-Grenadines', code: 'VC', flag: '🇻🇨', dialCode: '1-784' },
  { name: 'Salvador', code: 'SV', flag: '🇸🇻', dialCode: '503' },
  { name: 'Samoa', code: 'WS', flag: '🇼🇸', dialCode: '685' },
  { name: 'Saint-Marin', code: 'SM', flag: '🇸🇲', dialCode: '378' },
  { name: 'Sao Tomé-et-Principe', code: 'ST', flag: '🇸🇹', dialCode: '239' },
  { name: 'Sénégal', code: 'SN', flag: '🇸🇳', dialCode: '221' },
  { name: 'Serbie', code: 'RS', flag: '🇷🇸', dialCode: '381' },
  { name: 'Seychelles', code: 'SC', flag: '🇸🇨', dialCode: '248' },
  { name: 'Sierra Leone', code: 'SL', flag: '🇸🇱', dialCode: '232' },
  { name: 'Singapour', code: 'SG', flag: '🇸🇬', dialCode: '65' },
  { name: 'Slovaquie', code: 'SK', flag: '🇸🇰', dialCode: '421' },
  { name: 'Slovénie', code: 'SI', flag: '🇸🇮', dialCode: '386' },
  { name: 'Somalie', code: 'SO', flag: '🇸🇴', dialCode: '252' },
  { name: 'Soudan', code: 'SD', flag: '🇸🇩', dialCode: '249' },
  { name: 'Soudan du Sud', code: 'SS', flag: '🇸🇸', dialCode: '211' },
  { name: 'Sri Lanka', code: 'LK', flag: '🇱🇰', dialCode: '94' },
  { name: 'Suède', code: 'SE', flag: '🇸🇪', dialCode: '46' },
  { name: 'Suisse', code: 'CH', flag: '🇨🇭', dialCode: '41' },
  { name: 'Suriname', code: 'SR', flag: '🇸🇷', dialCode: '597' },
  { name: 'Syrie', code: 'SY', flag: '🇸🇾', dialCode: '963' },
  { name: 'Tadjikistan', code: 'TJ', flag: '🇹🇯', dialCode: '992' },
  { name: 'Tanzanie', code: 'TZ', flag: '🇹🇿', dialCode: '255' },
  { name: 'Tchad', code: 'TD', flag: '🇹🇩', dialCode: '235' },
  { name: 'Tchéquie', code: 'CZ', flag: '🇨🇿', dialCode: '420' },
  { name: 'Thaïlande', code: 'TH', flag: '🇹🇭', dialCode: '66' },
  { name: 'Timor oriental', code: 'TL', flag: '🇹🇱', dialCode: '670' },
  { name: 'Togo', code: 'TG', flag: '🇹🇬', dialCode: '228' },
  { name: 'Tonga', code: 'TO', flag: '🇹🇴', dialCode: '676' },
  { name: 'Trinité-et-Tobago', code: 'TT', flag: '🇹🇹', dialCode: '1-868' },
  { name: 'Tunisie', code: 'TN', flag: '🇹🇳', dialCode: '216' },
  { name: 'Turkménistan', code: 'TM', flag: '🇹🇲', dialCode: '993' },
  { name: 'Turquie', code: 'TR', flag: '🇹🇷', dialCode: '90' },
  { name: 'Tuvalu', code: 'TV', flag: '🇹🇻', dialCode: '688' },
  { name: 'Ukraine', code: 'UA', flag: '🇺🇦', dialCode: '380' },
  { name: 'Uruguay', code: 'UY', flag: '🇺🇾', dialCode: '598' },
  { name: 'Vanuatu', code: 'VU', flag: '🇻🇺', dialCode: '678' },
  { name: 'Vatican', code: 'VA', flag: '🇻🇦', dialCode: '379' },
  { name: 'Venezuela', code: 'VE', flag: '🇻🇪', dialCode: '58' },
  { name: 'Viêt Nam', code: 'VN', flag: '🇻🇳', dialCode: '84' },
  { name: 'Yémen', code: 'YE', flag: '🇾🇪', dialCode: '967' },
  { name: 'Zambie', code: 'ZM', flag: '🇿🇲', dialCode: '260' },
  { name: 'Zimbabwe', code: 'ZW', flag: '🇿🇼', dialCode: '263' },
];